#!/usr/bin/env bash
# =============================================================================
#  gen-certs.sh — generate a private CA + broker (server) cert + device (client)
#  cert for the Rental Monitor's mutual-TLS MQTT link.
#
#  Run from anywhere; output lands in ./certs next to this script. Re-running
#  regenerates leaf certs against the EXISTING CA (so already-deployed devices
#  keep trusting the broker). Delete certs/ca.* first to rotate the CA too.
#
#  After generating, refresh the firmware secrets header with:
#      ./gen-certs.sh --header ../include/secrets/ca_cert.h
#
#  Requires: openssl (1.1.1+ / 3.x).
# =============================================================================
set -euo pipefail

# ---- tunables (override via env) --------------------------------------------
BROKER_HOST="${BROKER_HOST:-broker.example.com}"   # must match MQTT_HOST in config.h
DEVICE_ID="${DEVICE_ID:-rental-mon-01}"           # must match DEVICE_ID / MQTT_USERNAME
DAYS_CA="${DAYS_CA:-3650}"                         # 10y — CA
DAYS_LEAF="${DAYS_LEAF:-3650}"                     # 10y — node is inaccessible; long-lived
RSA_CA_BITS="${RSA_CA_BITS:-4096}"
RSA_LEAF_BITS="${RSA_LEAF_BITS:-2048}"             # 2048 keeps ESP32 handshake light

cd "$(dirname "$0")"
CERTS=certs
mkdir -p "$CERTS"

# ---- optional: (re)emit the firmware secrets header, then exit --------------
if [[ "${1:-}" == "--header" ]]; then
  OUT="${2:?usage: $0 --header <path/to/ca_cert.h>}"
  {
    echo "// AUTO-GENERATED by mosquitto/gen-certs.sh — do not edit by hand."
    echo "// Contains the broker CA (to verify the server) and this device's"
    echo "// client cert + key (mutual TLS). This file is git-ignored."
    echo "#pragma once"
    echo
    echo "static const char MQTT_CA_CERT[] PROGMEM = R\"EOF("
    cat "$CERTS/ca.crt"
    echo ")EOF\";"
    echo
    echo "#define MQTT_CLIENT_CERT MQTT_CLIENT_CERT_PEM"
    echo "static const char MQTT_CLIENT_CERT_PEM[] PROGMEM = R\"EOF("
    cat "$CERTS/client.crt"
    echo ")EOF\";"
    echo
    echo "#define MQTT_CLIENT_KEY MQTT_CLIENT_KEY_PEM"
    echo "static const char MQTT_CLIENT_KEY_PEM[] PROGMEM = R\"EOF("
    cat "$CERTS/client.key"
    echo ")EOF\";"
  } > "$OUT"
  echo "wrote $OUT"
  exit 0
fi

# ---- 1. CA (create once; reuse on re-run) -----------------------------------
if [[ ! -f "$CERTS/ca.key" || ! -f "$CERTS/ca.crt" ]]; then
  echo "==> generating CA"
  openssl genrsa -out "$CERTS/ca.key" "$RSA_CA_BITS"
  chmod 600 "$CERTS/ca.key"
  openssl req -x509 -new -nodes -key "$CERTS/ca.key" -sha256 -days "$DAYS_CA" \
    -subj "/O=Rental Monitor/CN=Rental Monitor CA" -out "$CERTS/ca.crt"
else
  echo "==> reusing existing CA (delete certs/ca.* to rotate)"
fi

# ---- 2. Broker (server) cert ------------------------------------------------
echo "==> generating server cert for CN=$BROKER_HOST"
openssl genrsa -out "$CERTS/server.key" "$RSA_LEAF_BITS"
chmod 600 "$CERTS/server.key"
openssl req -new -key "$CERTS/server.key" \
  -subj "/O=Rental Monitor/CN=$BROKER_HOST" -out "$CERTS/server.csr"
cat > "$CERTS/server.ext" <<EOF
basicConstraints=CA:FALSE
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
subjectAltName=DNS:$BROKER_HOST,DNS:localhost,IP:127.0.0.1
EOF
openssl x509 -req -in "$CERTS/server.csr" -CA "$CERTS/ca.crt" -CAkey "$CERTS/ca.key" \
  -CAcreateserial -days "$DAYS_LEAF" -sha256 -extfile "$CERTS/server.ext" \
  -out "$CERTS/server.crt"

# ---- 3. Device (client) cert ------------------------------------------------
echo "==> generating client cert for CN=$DEVICE_ID"
openssl genrsa -out "$CERTS/client.key" "$RSA_LEAF_BITS"
chmod 600 "$CERTS/client.key"
openssl req -new -key "$CERTS/client.key" \
  -subj "/O=Rental Monitor/CN=$DEVICE_ID" -out "$CERTS/client.csr"
cat > "$CERTS/client.ext" <<EOF
basicConstraints=CA:FALSE
keyUsage=digitalSignature
extendedKeyUsage=clientAuth
subjectAltName=DNS:$DEVICE_ID
EOF
openssl x509 -req -in "$CERTS/client.csr" -CA "$CERTS/ca.crt" -CAkey "$CERTS/ca.key" \
  -CAcreateserial -days "$DAYS_LEAF" -sha256 -extfile "$CERTS/client.ext" \
  -out "$CERTS/client.crt"

rm -f "$CERTS"/*.csr "$CERTS"/*.ext
echo
echo "Done. Files in $CERTS/:"
echo "  ca.crt      -> broker (cafile) + firmware (MQTT_CA_CERT)"
echo "  server.crt/key -> broker (certfile/keyfile)"
echo "  client.crt/key -> firmware (MQTT_CLIENT_CERT/KEY)"
echo
echo "Next: ./gen-certs.sh --header ../include/secrets/ca_cert.h"
